version: '3'
services:
        web:
                image: flask_barn_v123
                build: .
                ports:
                        - "8867:8867"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped