version: '3'
services:
        web:
                image: flask_barn_v02
                build: .
                ports:
                        - "8222:8086"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped