version: '3'
services:
        web:
                image: flask_barn_v891
                build: .
                ports:
                        - "8924:8924"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped