version: '3'
services:
        web:
                image: flask_barn_v999
                build: .
                ports:
                        - "8444:8086"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped