version: '3'
services:
        web:
                image: flask_barn_v891
                build: .
                ports:
                        - "8953:8953"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped