version: '3'
services:
        web:
                image: flask_barn_v222
                build: .
                ports:
                        - "8282:8086"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped